Add heatmap
PENQEinc/metastanza pull request #4
Opened 2021-09-07 06:34 UTC by teraomoyu

heatmapを追加しました。
高さ、横幅、padding、横軸のラベル（数は固定）、色を変えるようにしました。

2021-09-07 07:16 UTC, MarleenEliza reviewed
コメントを確認してください

2021-09-07 07:16 UTC, MarleenEliza commented on stanzas/heatmap/index.js
> +                      this.params["label10"]];
申し訳ありませんが、この辺りは将来にデータ内で設定するようになりますので、Paramsにしなくて良いです。

2021-09-07 07:16 UTC, MarleenEliza commented on stanzas/heatmap/metadata.json
> +    }
GreetingはただのDummyデータだったのでこのParamを削除してください。

2021-09-07 07:16 UTC, MarleenEliza commented on stanzas/heatmap/style.scss
> +}
こちらもDummyデータなので削除してOK。もし寺尾さんが開発の時にこちらをサンプルとしてみたかったらコメントアウトしても問題です。
できるだけ最初の段階から要らないものをファイルから削除すると後でRefactoringなどが楽になります。

2021-09-07 07:16 UTC, MarleenEliza commented on stanzas/heatmap/index.js
> +  async render() {
コード全体的な大きな問題点ですが、HeatmapはResponsiveになっていません。下記のようにParamsを変更すると新しいHeatmapが作られてしまいます。こちらは対応できそうですか？
おそらくRenderingの問題だと思います。（d3.select.appendで毎回新しいSVGがAppendされている）
manhattan-plotのindex.jsを参考にしてこちらを優先的に対応してもらえますでしょうか？

![image](https://user-images.githubusercontent.com/62828450/132300193-c69f7dd4-6811-4ea7-a508-b5ca241c76da.png)

2021-09-07 07:27 UTC, MarleenEliza commented
@teraomoyu 、
レビューが終わりました。次に下記の流れで進みたいと思っております。

1. まずはレビューを確認して必要な修正をお願いできますでしょうか？
2. それが完了したら再度このadd_heatmapのブランチに修正をPushし、ご連絡をいただければと思います。
3. 私がコードをレビューします。
4. 次に次のParamsの追加をお願いしたいと思います　`--togostanza-font-family, --togostanza-title-font-color, --togostanza-title-font-weight, --togostanza-hover-color`
5. そちらもPushしてコードレビューに入ります。
6. ５が終わったらデータの構成を一緒にセットアップできればと思います。

どのタイミングでも不明な点・解決できない問題があったらお気軽にお知らせください。レビューに関しての質問ももちろんOKです。

2021-12-16 07:16 UTC, MarleenEliza requested changes
@teraomoyu 対応ありがとうございます！
次に以下の対応をお願いできますか？
1. 最新のmainブランチに合わせる
→ 今回はMainのブランチのものを全部受け取りたい`git merge main --strategy-option ours `でマージしてください
2. 現在のPRはチェックに落ちたらしいです。この間話してたLintが原因のようです。解決してもらってもいいですか？
→ `npm run lint`でエラーが確認できます。
→ `npm run lint:fix:`で自動に修正できるエラーは自動的に修正してくれます。
3. 不要なコード（コメントアウトされたもの）を削除してください。

また、社内にPRのレビューをもう少しちゃんとしたい話になりました。そのため、レビューする側にもスムーズにレビューできるために今後レビューをお願いする前に以下を用意していただけますか？（PRのルールはここで確認できます：https://github.com/PENQEinc/metastanza/wiki/PENQE%E7%A4%BE%E5%86%85-%E3%83%A1%E3%83%A2）
1. 最新の`main`ブランチとMergeし、Conflictを全部解決する。
2. Githubのチェックが全部合格しているようにPRを更新する。
3. 対応したことをPRのコメントにリストアップする。
4. 自信がないところ・うまくできなかったことがあればPRのコメントに残す。

もちろん上記で何か不明な点・うまく対応できなかったこと（mainとmergeする時のConflictをどうすればいいか分からないときなど）があればご気軽にお知らせください！

2021-12-16 07:16 UTC, MarleenEliza commented on stanzas/heatmap/index.js
> +// import { render } from "@vue/runtime-dom";
不要なコードを削除してください（他のところにもあります）

2021-12-17 05:03 UTC, MarleenEliza commented
@teraomoyu ありがとうございます！
1. package-lockだけがConflictを起こしているようなので以下の手順も行ってください：
- `npm i`でNode Jsをインストールする。
- package-lock.jsonファイルファ変更されるはず。それをCommitしPushしてください。
4. とりあえずOKです

新しいレビューコメントを書いたのでそれもご確認ください。よろしくお願いします。

2021-12-17 15:04 UTC, teraomoyu commented
前回最新のものをpullしていなかったのでpullし直してマージしました。
新しいレビューコメントはどこで見れますか？

2021-12-20 07:59 UTC, teraomoyu commented
--togostanza-font-family, --togostanza-title-font-color, --togostanza-title-font-weight, --togostanza-hover-colorの４つのパラメータを追加しましたfont familyとcolor、weightはラベルに反映しました。

hoverについてはどのような機能にすれば良いでしょうか？

2022-02-14 06:25 UTC, closed without merging