Add treemap
PENQEinc/metastanza pull request #5
Opened 2021-11-01 05:35 UTC by neznayer

Added zoomable Treemap.

2021-11-10 11:40 UTC, penqe approved these changes

2021-11-10 11:42 UTC, penqe commented
コードはざっとみた限り問題なさそうです。
ですが、アントンさんと関係ないところでコンフリクトがいっぱい出てますね。。
自分も同じようなことが起こりました。
どのように解決するのが最適か分からないので、金曜か、パッチさんが出勤する水曜に相談させてください。

2021-12-04 00:30 UTC, penqe approved these changes

2021-12-04 00:31 UTC, penqe commented
@neznayer treemap をマージしようとしたら、コンフリクトがあるようです。確認していただけますか。

2021-12-07 04:25 UTC, penqe requested changes

2021-12-07 04:25 UTC, penqe commented on package.json
> +    "lit-element": "^3.0.1",
重複してるようです。

2021-12-07 04:38 UTC, neznayer reviewed
すみません、ありがおうございます！

2021-12-07 04:38 UTC, neznayer commented on package.json
> +    "lit-element": "^3.0.1",
ありがとうございます！

2021-12-07 05:42 UTC, penqe approved these changes

2021-12-07 05:42 UTC, penqe commented
@neznayer ありがとうございますー！

2021-12-07 05:42 UTC, merged